# Generated by Django 5.2.1 on 2025-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_add_protocol_to_vaultprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultAPY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vault_address",
                    models.CharField(
                        help_text="The vault contract address", max_length=255
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        help_text="The token symbol, e.g., USDe, USDT0",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "apy_24h",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="24-hour APY calculation",
                        max_digits=20,
                    ),
                ),
                (
                    "midnight_share_price",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Share price at midnight",
                        max_digits=20,
                    ),
                ),
                (
                    "current_share_price",
                    models.DecimalField(
                        decimal_places=8, help_text="Current share price", max_digits=20
                    ),
                ),
                (
                    "apy_7d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="7-day APY calculation",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "seven_day_share_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Share price from 7 days ago",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "days_elapsed",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Days elapsed for calculation",
                        max_digits=10,
                    ),
                ),
                (
                    "exponential",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Exponential factor used in calculation",
                        max_digits=10,
                    ),
                ),
                (
                    "calculation_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this calculation was performed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vault APY",
                "verbose_name_plural": "Vault APYs",
                "ordering": ["-calculation_time"],
                "indexes": [
                    models.Index(
                        fields=["vault_address", "-calculation_time"],
                        name="data_vaulta_vault_a_271606_idx",
                    ),
                    models.Index(
                        fields=["-calculation_time"],
                        name="data_vaulta_calcula_ad0a21_idx",
                    ),
                ],
            },
        ),
    ]
