# Generated by Django 5.2.5 on 2025-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_vault_withdrawal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='yieldreport',
            name='params',
            field=models.TextField(default='{}'),
        ),
    ]
