# Generated by Django 5.2.1 on 2025-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_yieldreport_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultRebalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rebalance_id",
                    models.CharField(
                        help_text="Unique ID for the rebalance operation", max_length=64
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("withdrawal", "Withdrawal"), ("deposit", "Deposit")],
                        help_text="Type of transaction: withdrawal or deposit",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of the transaction",
                        max_length=20,
                    ),
                ),
                (
                    "from_protocol",
                    models.CharField(
                        blank=True,
                        help_text="Source protocol name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "to_protocol",
                    models.CharField(
                        blank=True,
                        help_text="Destination protocol name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "from_pool_address",
                    models.CharField(
                        blank=True,
                        help_text="Source pool address",
                        max_length=42,
                        null=True,
                    ),
                ),
                (
                    "to_pool_address",
                    models.CharField(
                        blank=True,
                        help_text="Destination pool address",
                        max_length=42,
                        null=True,
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=18,
                        default=0,
                        help_text="USD value of the transaction",
                        max_digits=30,
                    ),
                ),
                (
                    "amount_token",
                    models.DecimalField(
                        decimal_places=18,
                        default=0,
                        help_text="Token amount in decimal format",
                        max_digits=78,
                    ),
                ),
                (
                    "amount_token_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw token amount (wei)",
                        max_length=78,
                        null=True,
                    ),
                ),
                (
                    "token_symbol",
                    models.CharField(
                        default="USDe", help_text="Token symbol", max_length=10
                    ),
                ),
                (
                    "token_decimals",
                    models.IntegerField(default=18, help_text="Token decimals"),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True,
                        help_text="Transaction hash",
                        max_length=66,
                        null=True,
                    ),
                ),
                (
                    "block_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Block number where transaction was confirmed",
                        null=True,
                    ),
                ),
                (
                    "gas_used",
                    models.BigIntegerField(
                        blank=True, help_text="Gas used for the transaction", null=True
                    ),
                ),
                (
                    "gas_price",
                    models.BigIntegerField(
                        blank=True, help_text="Gas price in wei", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if transaction failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated"
                    ),
                ),
            ],
            options={
                "db_table": "vault_rebalance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="vaultwithdrawalrun",
            name="asset_decimals",
            field=models.IntegerField(default=18, help_text="Token decimals"),
        ),
        migrations.AddField(
            model_name="vaultwithdrawalrun",
            name="asset_symbol",
            field=models.CharField(
                default="USDe", help_text="Token symbol", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="vaultwithdrawalrun",
            name="total_withdrawal_amount",
            field=models.BigIntegerField(
                default=0, help_text="Total amount withdrawn in token units"
            ),
        ),
        migrations.AddField(
            model_name="vaultwithdrawalrun",
            name="total_withdrawal_amount_formatted",
            field=models.DecimalField(
                decimal_places=18,
                default=0,
                help_text="Total amount withdrawn in human-readable format",
                max_digits=30,
            ),
        ),
    ]
