# Generated by Django 5.2.1 on 2025-09-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_vaultrebalance_vaultwithdrawalrun_asset_decimals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultdepositrun",
            name="best_pool_address",
            field=models.CharField(
                blank=True,
                help_text="Address of the best pool selected for deposit",
                max_length=42,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaultdepositrun",
            name="best_pool_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the best protocol/pool selected for deposit",
                max_length=50,
                null=True,
            ),
        ),
    ]
