# Generated by Django 5.2.1 on 2025-09-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_vaultdepositrun_best_pool_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultrebalance",
            name="strategy_summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated summary of the rebalancing strategy",
                null=True,
            ),
        ),
    ]
