# Generated by Django 5.2.1 on 2025-09-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0011_vaultrebalance_strategy_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaultdepositrun",
            name="idle_assets_before",
            field=models.CharField(
                default="0",
                help_text="Idle assets in vault before deposit in wei (stored as string to avoid numeric overflow)",
                max_length=78,
            ),
        ),
        migrations.AlterField(
            model_name="vaultdepositrun",
            name="total_assets_to_deposit",
            field=models.CharField(
                default="0",
                help_text="Total assets to deposit in wei (stored as string to avoid numeric overflow)",
                max_length=78,
            ),
        ),
    ]
